### PR TITLE
Migrate to TypeScript; Remove Dockerfile

### PR DESCRIPTION
**Pull request by vladkens**
Hi. I like your project, I use it in my actions. 

But I didn't like that it required a docker build every time to work (https://github.com/ravsamhq/notify-slack-action/issues/47). I looked that there is an open issue (https://github.com/ravsamhq/notify-slack-action/issues/38) to rewrite the project to JavaScript using GitHub native libraries for actions (to run without docker).

I rewrote the code from Python to TypeScript, as described in the official GitHub example: https://github.com/actions/typescript-action/

I also added tests and correct readme. Checked in my actions - it works as before, only you don't have to wait 17 seconds each time for Docker to build 😃

I hope you will accept this PR. Good luck!

### CODE REVIEW

**Comment by ravgeetdhillon** [comment]
@vladkens You have really done a great job! I'll need some time to review the PR but I'll do so as quickly as possible. Once again, thank you so much for your work.

**Review by ravgeetdhillon — APPROVED** [review]
LGTM

**Comment by ulgens** [comment]
@ravgeetdhillon Any plans for a new release with this change?

**Comment by ravgeetdhillon** [comment]
@ulgens Currently, I'm testing this in a private repo to make sure everything works as expected. Hopefully, I'll release a v2 this weekend.

**Comment by ulgens** [comment]
@ravgeetdhillon Got it, thanks a lot.

**Pull request merged**
